ROOT     := $(CURDIR)
GAME_DIR := $(ROOT)/game
TARGET   := mipsel-sony-psx
DIST     := $(ROOT)/dist
GAME_EXE := $(GAME_DIR)/target/$(TARGET)/release/plattypus.exe
MKISOPSX := $(ROOT)/psoxide/tools/mkisopsx

.PHONY: all exe disc clean run test help check-media video-bench video-bench-build

all: disc

help:
	@echo "Plattypus (PSX / PSoXide) Build Targets:"
	@echo "  make exe         - Compile PSX-EXE (MIPS R3000 bare-metal binary)"
	@echo "  make disc        - Master bootable PS1 disc image (dist/plattypus.{bin,cue})"
	@echo "  make test        - Run automated host-side game logic test suite"
	@echo "  make run         - Run disc in DuckStation, RetroArch, or EMULATOR=... emulator"
	@echo "  make check-media - Verify the disc image is well formed"
	@echo "  make video-bench - Measure intro-video playback performance (needs an emulator)"
	@echo "  make clean       - Clean build artifacts"
	@echo ""
	@echo "Video performance options:"
	@echo "  RUNS=N     - repeat the measurement N times and report the median (default 1)"
	@echo "  SECONDS=N  - wall-clock budget per run (default 150; a full run takes ~60s)"

test:
	cargo run --manifest-path $(ROOT)/tools/test_game_logic/Cargo.toml

# ---------------------------------------------------------------------------
# Intro-video performance measurement.
#
# Builds video_bench (a PSX-EXE that plays the intro through the game's own
# video.rs with a stopwatch attached), masters a disc holding it plus
# INTRO.VID, runs it headless, and writes dist/video_bench_report.json.
# See tools/video_bench/README.md for the metric definitions.
# ---------------------------------------------------------------------------
RUNS    ?= 1
SECONDS ?= 150

video-bench:
	python3 $(ROOT)/tools/video_bench/host_bench.py --runs $(RUNS) --seconds $(SECONDS)

video-bench-build:
	cd $(ROOT)/video_bench && cargo build --release

exe:
	@mkdir -p $(DIST)
	cd $(GAME_DIR) && cargo build --release
	@cp $(GAME_EXE) $(DIST)/plattypus.exe
	@echo "BUILT PSX-EXE -> $(DIST)/plattypus.exe"

disc: exe check-media
	@mkdir -p $(DIST)
	cargo run --release --manifest-path $(MKISOPSX)/Cargo.toml -- \
		--exe $(DIST)/plattypus.exe \
		--out $(DIST)/plattypus.bin \
		--volume PLATTYPUS \
		--cdda-track $(ROOT)/Music/title_music.cdda \
		--str-file $(ROOT)/Videos/INTRO.STR \
		--str-file $(ROOT)/Videos/INTRO.VID \
		--str-file $(ROOT)/Videos/OUTRO.STR \
		--str-file $(ROOT)/Videos/OUTRO.VID
	@echo "SUCCESS! Bootable PS1 Disc Mastered:"
	@echo "  CUE: $(DIST)/plattypus.cue"
	@echo "  BIN: $(DIST)/plattypus.bin"

# The media inputs are large binaries that are not generated by any target, so
# a missing one used to surface as an opaque failure inside mkisopsx.
check-media:
	@missing=""; \
	for f in Music/title_music.cdda Videos/INTRO.STR Videos/INTRO.VID \
	         Videos/OUTRO.STR Videos/OUTRO.VID; do \
		[ -f "$(ROOT)/$$f" ] || missing="$$missing $$f"; \
	done; \
	if [ -n "$$missing" ]; then \
		echo "ERROR: missing disc media:$$missing"; \
		echo "These are not build outputs. Restore them from your asset store."; \
		exit 1; \
	fi

run: disc
	@if [ -n "$$EMULATOR" ]; then \
		"$$EMULATOR" "$(DIST)/plattypus.cue"; \
	elif [ -f "$$DUCKSTATION_APPIMAGE" ] && [ -n "$$DUCKSTATION_APPIMAGE" ]; then \
		echo "Launching $(DIST)/plattypus.cue in DuckStation AppImage..."; \
		APPIMAGE_EXTRACT_AND_RUN=1 "$$DUCKSTATION_APPIMAGE" "$(DIST)/plattypus.cue"; \
	elif command -v duckstation >/dev/null 2>&1; then \
		echo "Launching $(DIST)/plattypus.cue in DuckStation..."; \
		duckstation "$(DIST)/plattypus.cue"; \
	elif command -v duckstation-qt >/dev/null 2>&1; then \
		echo "Launching $(DIST)/plattypus.cue in DuckStation (Qt)..."; \
		duckstation-qt "$(DIST)/plattypus.cue"; \
	elif command -v retroarch >/dev/null 2>&1; then \
		echo "Launching $(DIST)/plattypus.cue in RetroArch..."; \
		retroarch "$(DIST)/plattypus.cue"; \
	else \
		echo "Please open $(DIST)/plattypus.cue in your PS1 emulator (DuckStation, RetroArch, etc.)."; \
		echo "Set EMULATOR=/path/to/emulator to launch one directly."; \
	fi

clean:
	cd $(GAME_DIR) && cargo clean
	rm -rf $(DIST)
