[build]
target = "mipsel-sony-psx"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.mipsel-sony-psx]
rustflags = ["-C", "llvm-args=-disable-mips-df-backward-search"]
