//! Built-in ADPCM tone samples.
//!
//! Each tone is a single 16-byte ADPCM block with self-loop flags
//! set (0x07 = loop end + repeat + loop start), so the SPU
//! sustains the waveform until [`crate::Voice::key_off`]. Native
//! playback frequency at [`crate::Pitch::UNITY`] is ~1575 Hz
//! (44100 / 28 samples per loop); use [`crate::Pitch::for_frequency`]
//! to tune to a specific note.
//!
//! Generated by `psoxide-dev gen-tones` from hand-rolled waveform
//! definitions - no external dependency on an ADPCM encoder.

/// Native playback frequency (Hz) when a single-block
/// tone is played at [`crate::Pitch::UNITY`]. The 28-sample
/// loop at 44100 Hz gives 44100 / 28 = 1575 Hz.
pub const NATIVE_HZ: u32 = 1575;

/// Pure sine wave. Smooth, tonal - the default tuning reference.
pub const SINE: &[u8; 16] = include_bytes!("../vendor/tone_sine.adpcm");

/// Hard square wave. Buzzier, classic 8-bit timbre.
pub const SQUARE: &[u8; 16] = include_bytes!("../vendor/tone_square.adpcm");

/// Triangle wave. Softer than square, richer than sine.
pub const TRIANGLE: &[u8; 16] = include_bytes!("../vendor/tone_triangle.adpcm");

/// Sawtooth ramp. Bright, full-spectrum - good for chiptune leads.
pub const SAWTOOTH: &[u8; 16] = include_bytes!("../vendor/tone_sawtooth.adpcm");
