//! Built-in fonts.
//!
//! Mostly from dhepper/font8x8 (8x8 monochrome), the canonical
//! IBM PC VGA 8x16 font (the PC BIOS font, unrelated to the PS1
//! BIOS), and a curated set of commercially usable TTFs rasterized
//! into compact PS1 cells.
//! See `vendor/PROVENANCE.md` for the full chain.
//!
//! Generated by `psoxide-dev gen-fonts`. Add new entries there
//! rather than editing this file by hand.

/// Built-in font: `basic` (U+0000..U+007F, 128 glyphs).
pub mod basic;
/// Built-in font: `ext_latin` (U+00A0..U+00FF, 96 glyphs).
pub mod ext_latin;
/// Built-in font: `boxdraw` (U+2500..U+257F, 128 glyphs).
pub mod boxdraw;
/// Built-in font: `basic_8x16` (U+0000..U+007F, 128 glyphs).
pub mod basic_8x16;
/// Built-in font: `kenney_blocks` (U+0020..U+007F, 96 glyphs).
pub mod kenney_blocks;
/// Built-in font: `kenney_future` (U+0020..U+007F, 96 glyphs).
pub mod kenney_future;
/// Built-in font: `kenney_future_narrow` (U+0020..U+007F, 96 glyphs).
pub mod kenney_future_narrow;
/// Built-in font: `kenney_high` (U+0020..U+007F, 96 glyphs).
pub mod kenney_high;
/// Built-in font: `kenney_high_square` (U+0020..U+007F, 96 glyphs).
pub mod kenney_high_square;
/// Built-in font: `kenney_mini` (U+0020..U+007F, 96 glyphs).
pub mod kenney_mini;
/// Built-in font: `kenney_mini_square` (U+0020..U+007F, 96 glyphs).
pub mod kenney_mini_square;
/// Built-in font: `kenney_mini_square_mono` (U+0020..U+007F, 96 glyphs).
pub mod kenney_mini_square_mono;
/// Built-in font: `kenney_pixel` (U+0020..U+007F, 96 glyphs).
pub mod kenney_pixel;
/// Built-in font: `kenney_pixel_square` (U+0020..U+007F, 96 glyphs).
pub mod kenney_pixel_square;
/// Built-in font: `kenney_rocket` (U+0020..U+007F, 96 glyphs).
pub mod kenney_rocket;
/// Built-in font: `kenney_rocket_square` (U+0020..U+007F, 96 glyphs).
pub mod kenney_rocket_square;
/// Built-in font: `press_start_2p` (U+0020..U+007F, 96 glyphs).
pub mod press_start_2p;
/// Built-in font: `silkscreen` (U+0020..U+007F, 96 glyphs).
pub mod silkscreen;
/// Built-in font: `pixelify_sans` (U+0020..U+007F, 96 glyphs).
pub mod pixelify_sans;
/// Built-in font: `orbitron` (U+0020..U+007F, 96 glyphs).
pub mod orbitron;
/// Built-in font: `audiowide` (U+0020..U+007F, 96 glyphs).
pub mod audiowide;
/// Built-in font: `michroma` (U+0020..U+007F, 96 glyphs).
pub mod michroma;
/// Built-in font: `electrolize` (U+0020..U+007F, 96 glyphs).
pub mod electrolize;
/// Built-in font: `oxanium` (U+0020..U+007F, 96 glyphs).
pub mod oxanium;
/// Built-in font: `rajdhani` (U+0020..U+007F, 96 glyphs).
pub mod rajdhani;
/// Built-in font: `chakra_petch` (U+0020..U+007F, 96 glyphs).
pub mod chakra_petch;
/// Built-in font: `tektur` (U+0020..U+007F, 96 glyphs).
pub mod tektur;
/// Built-in font: `tomorrow` (U+0020..U+007F, 96 glyphs).
pub mod tomorrow;
/// Built-in font: `zen_dots` (U+0020..U+007F, 96 glyphs).
pub mod zen_dots;
/// Built-in font: `turret_road` (U+0020..U+007F, 96 glyphs).
pub mod turret_road;
/// Built-in font: `tiny5` (U+0020..U+007F, 96 glyphs).
pub mod tiny5;
/// Built-in font: `jersey_10` (U+0020..U+007F, 96 glyphs).
pub mod jersey_10;
/// Built-in font: `space_mono` (U+0020..U+007F, 96 glyphs).
pub mod space_mono;
/// Built-in font: `bruno_ace` (U+0020..U+007F, 96 glyphs).
pub mod bruno_ace;
/// Built-in font: `aldrich` (U+0020..U+007F, 96 glyphs).
pub mod aldrich;
/// Built-in font: `syncopate` (U+0020..U+007F, 96 glyphs).
pub mod syncopate;
/// Built-in font: `share_tech_mono` (U+0020..U+007F, 96 glyphs).
pub mod share_tech_mono;
/// Built-in font: `jura` (U+0020..U+007F, 96 glyphs).
pub mod jura;
/// Built-in font: `drippy_space` (U+0020..U+005A, 59 glyphs).
pub mod drippy_space;
/// Built-in font: `drippy_space_display` (U+0041..U+005A, 26 glyphs).
pub mod drippy_space_display;
/// Built-in font: `zen_dots_display` (U+0041..U+005A, 26 glyphs).
pub mod zen_dots_display;

// Flat re-exports so call sites read as
// `psx_font::fonts::BASIC` etc.
pub use basic::BASIC;
pub use ext_latin::EXT_LATIN;
pub use boxdraw::BOXDRAW;
pub use basic_8x16::BASIC_8X16;
pub use kenney_blocks::KENNEY_BLOCKS;
pub use kenney_future::KENNEY_FUTURE;
pub use kenney_future_narrow::KENNEY_FUTURE_NARROW;
pub use kenney_high::KENNEY_HIGH;
pub use kenney_high_square::KENNEY_HIGH_SQUARE;
pub use kenney_mini::KENNEY_MINI;
pub use kenney_mini_square::KENNEY_MINI_SQUARE;
pub use kenney_mini_square_mono::KENNEY_MINI_SQUARE_MONO;
pub use kenney_pixel::KENNEY_PIXEL;
pub use kenney_pixel_square::KENNEY_PIXEL_SQUARE;
pub use kenney_rocket::KENNEY_ROCKET;
pub use kenney_rocket_square::KENNEY_ROCKET_SQUARE;
pub use press_start_2p::PRESS_START_2P;
pub use silkscreen::SILKSCREEN;
pub use pixelify_sans::PIXELIFY_SANS;
pub use orbitron::ORBITRON;
pub use audiowide::AUDIOWIDE;
pub use michroma::MICHROMA;
pub use electrolize::ELECTROLIZE;
pub use oxanium::OXANIUM;
pub use rajdhani::RAJDHANI;
pub use chakra_petch::CHAKRA_PETCH;
pub use tektur::TEKTUR;
pub use tomorrow::TOMORROW;
pub use zen_dots::ZEN_DOTS;
pub use turret_road::TURRET_ROAD;
pub use tiny5::TINY5;
pub use jersey_10::JERSEY_10;
pub use space_mono::SPACE_MONO;
pub use bruno_ace::BRUNO_ACE;
pub use aldrich::ALDRICH;
pub use syncopate::SYNCOPATE;
pub use share_tech_mono::SHARE_TECH_MONO;
pub use jura::JURA;
pub use drippy_space::DRIPPY_SPACE;
pub use drippy_space_display::DRIPPY_SPACE_DISPLAY;
pub use zen_dots_display::ZEN_DOTS_DISPLAY;

// Hand-maintained fonts: no generator entry, kept as-is.
/// Hand-maintained built-in font module.
pub mod spleen_5x8;
pub use spleen_5x8::SPLEEN_5X8;
pub use spleen_5x8::SPLEEN_5X8_ITALIC;
